### PR TITLE
default input values

### PR DESCRIPTION
**Pull request by leon-thomm**

### CODE REVIEW

**Comment by leon-thomm** [comment]
CC: #23

Integrating default values for node inputs now seems simple using the new `Data` approach. I also just realized that default values could potentially solve a problem that emerged when trying to adapt ryvencore-qt (https://github.com/leon-thomm/Ryven/pull/137): widget values could be stored as default values. Hence, default values should be, in principle, mutable. I don't see a problem with that so far.

In the process I removed the IMO slightly ugly `add_data` field for node inputs. I kinda dislike the approach of dynamically attaching custom data to backend components from a frontend, which was the initial motivation, but I am not sure if there is a simple alternative. Comments on this appreciated.

**Comment by leon-thomm** [comment]
I'll merge this so we can continue moving forward with GUI adaptions. Feel free to comment if any issues with this arise later.

**Comment by amaury-anciaux** [comment]
Is it intentional that you merged it into main and not dev? Doesn't make a difference for me, but just to make sure I'm using the branches correctly.

**Comment by leon-thomm** [comment]
Yeah, I think if we depend on it in other repos, and since I don't think it fundamentally breaks anything, it can be on main, but one could argue for both (see https://github.com/leon-thomm/ryvencore/issues/26)

**Comment by amaury-anciaux** [comment]
It looks like `add_data` is currently used to store widget name, widget pos and widget state data so its removal is making PortItem unhappy. 
I'm not sure there is a way to better handle that data. The one thought I had is that there is some useless repetition in the code of a custom node by having to add the widget class to the `input_widget_classes` dict only to give the name to the `add_data` dict, so that could be simplified.

**Comment by leon-thomm** [comment]
Correct, that is the use I was aware of. I just dislike it because it's storing frontend-related data into specific components of the core, which smells like problems in the long run, and I feel like there should be easy solutions. I can think of those:

1. Store a global dict in the frontend which maps existing (input?) objects to the additional data, which we could then also nicely encode in a dataclass or something similar. We could store all such data here to nicely separate it from functionality.
2. Store it in the frontend component wrapper directly.

The second option sounds almost too obvious to me, but I can't remember why I did it this way, maybe we can look back into that. What do you think?

**Pull request merged**
